local _G = getfenv(0)

local f = CreateFrame('FRAME')
f:RegisterAllEvents()
f:UnregisterEvent('UPDATE_BINDINGS')
f:UnregisterEvent('UPDATE_BONUS_ACTIONBAR')
f:UnregisterEvent('UPDATE_CHAT_COLOR')
f:UnregisterEvent('UPDATE_CHAT_WINDOWS')
f:UnregisterEvent('UPDATE_INSTANCE_INFO')
f:UnregisterEvent('UPDATE_INVENTORY_ALERTS')
f:UnregisterEvent('UPDATE_FACTION')
f:UnregisterEvent('UPDATE_LFG_TYPES')
f:UnregisterEvent('UPDATE_MACROS')
f:UnregisterEvent('UPDATE_MOUSEOVER_UNIT')
f:UnregisterEvent('UPDATE_PENDING_MAIL')
f:UnregisterEvent('UPDATE_SHAPESHIFT_FORMS')
f:UnregisterEvent('UPDATE_TICKET')
f:UnregisterEvent('UPDATE_WORLD_STATES')
f:UnregisterEvent('ADDON_LOADED')
f:UnregisterEvent('VARIABLES_LOADED')
f:UnregisterEvent('FRIENDLIST_UPDATE')
f:UnregisterEvent('IGNORELIST_UPDATE')
f:UnregisterEvent('PLAYER_ALIVE')
f:UnregisterEvent('PLAYER_AURAS_CHANGED')
f:UnregisterEvent('PLAYER_CAMPING')
f:UnregisterEvent('PLAYER_GUILD_UPDATE')
f:UnregisterEvent('PLAYER_ENTERING_WORLD')
f:UnregisterEvent('PLAYER_LOGIN')
f:UnregisterEvent('PLAYER_TARGET_CHANGED')
f:UnregisterEvent('PLAYER_UNGHOST')
f:UnregisterEvent('UNIT_FLAGS')
f:UnregisterEvent('UNIT_LOYALTY')
f:UnregisterEvent('UNIT_MODEL_CHANGED')
f:UnregisterEvent('UNIT_NAME_UPDATE')
f:UnregisterEvent('UNIT_PORTRAIT_UPDATE')
f:UnregisterEvent('WORLD_MAP_UPDATE')
f:UnregisterEvent('MINIMAP_UPDATE_ZOOM')
f:UnregisterEvent('MINIMAP_ZONE_CHANGED')
f:UnregisterEvent('CHAT_MSG_SYSTEM')
f:UnregisterEvent('CHAT_MSG_CHANNEL_NOTICE')
f:UnregisterEvent('QUEST_LOG_UPDATE')
f:UnregisterEvent('PET_BAR_UPDATE')
f:UnregisterEvent('SKILL_LINES_CHANGED')
f:UnregisterEvent('MEETINGSTONE_CHANGED')
f:UnregisterEvent('TABARD_CANSAVE_CHANGED')
f:UnregisterEvent('LANGUAGE_LIST_CHANGED')
f:UnregisterEvent('SPELLS_CHANGED')
f:UnregisterEvent('SPELL_UPDATE_COOLDOWN')
f:UnregisterEvent('SPELL_UPDATE_USABLE')
f:UnregisterEvent('ACTIONBAR_SLOT_CHANGED')
f:UnregisterEvent('ACTIONBAR_UPDATE_COOLDOWN')
f:UnregisterEvent('ZONE_CHANGED_NEW_AREA')

f:SetScript('OnEvent', function()
	local s = event
	for i = 1, 50 do
		local a = _G['arg' .. i]
		if a then
			s = s .. ' | a' .. i .. '=' .. a
		end
	end
	SELECTED_CHAT_FRAME:AddMessage(s)
end)
